### ISSUE TITLE
Règles d'usage de ce repository

### ISSUE THREAD

**Issue by MamboJoel** [Lenormant/location#10]
# Introduction

Nous créons des "issues" qui sont des entrées pour remonter une anomalie, poser une question ou demander une amélioration et son auteur désigne un "assignee" qui est un responsable.
Ces options sont disponibles sur la droite.

# Responsables ou "Assignees"

Le responsable. Mais on peut intégrer des utilisateurs métier du groupe lenormant qui peuvent apporter des informations utiles pour la résolution de l'issue. Côté NTLM :
- Jean Lenormant : @jlenormant
- Damien Delbergue : @Portekoi
- Paulhac Lok : @Paulhac
- Jacques Meillere : @meillere
- Badr Eloifi : @badreloifi
- Nicolas Taret : @MamboJoel

# Labels

Une issue peut porter plusieurs "labels".

J'ai crée les "labels" suivants :

- question : une question sur le logiciel,
- amélioration : petit développement,
- bug : anomalie,
- à clôturer : le développement est terminé ou l'anomalie réglée et le développeur déclare qu'il attend la clôture de l'entrée,
- LCD : cette issue concerne la courte durée,
- LLD : cette issue concerne la longue durée.

Marie-Claire, si vous trouvez d'autres l

**Comment by MamboJoel** [comment]
Aussi, Marie-Clarire : je n'ai pas labellisé certaines issues au sens **LCD** ou **LLD**. Je vous invite le cas échéant à les documenter en les labellisant.

**Comment by HANNIERMC** [comment]
pour les labels ça me parait, à ce jour, suffisant. Ok je labellise les issues LCD ou LLD.

**Comment by jlenormant** [comment]
Comment peut-on gérer la priorité des demandes ? On pourrait avoir un label "prioritaire" pour les problèmes qui sont à régler au plus vite. Ou "priorité 1", "priorité 2", etc, si on veut faire des catégories plus fines. Qu'en pensez-vous ?

**Comment by HANNIERMC** [comment]
oui parfait
@MamboJoel

**Comment by MamboJoel** [comment]
@jlenormant  Ça me va aussi.

**Comment by HANNIERMC** [comment]
bonjour auriez vous quelques nouvelles de nos différentes demandes ?

**Comment by HANNIERMC** [comment]
bonjour auriez vous quelques nouvelles de nos différentes demandes ?

**Comment by MamboJoel** [comment]
Bonjour,

Nous sommes parvenus à installer les outils de développements sur les postes de plusieurs développeurs. J'interroge Jacques Meillere à propos de chaque issue afin d'établir un devis sur l'ensemble des travaux.

N'hésitez pas à utiliser les labels pour établir des priorités.

Merci !

Nicolas
