### ISSUE TITLE
LOCATION LLD creation d'un bouton

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#12]
[WAYBIS.docx](https://github.com/Lenormant/location/files/1767189/WAYBIS.docx)

Bonjour. demande d'amélioration en LLD pour création d'un bouton qui sélectionnerait toutes les factures.

**Comment by MamboJoel** [comment]
Note technique : il s'agit d'un javascript pour cocher toutes les checkbox.

**Comment by badreloifi** [comment]
Bonjour @HANNIERMC,
Pouvez-vous vérifier que  cela fonctionne et clore l'issue si résolu s'il vous plaît ?

**Comment by HANNIERMC** [comment]
bonjour non cela ne fonctionne pas .

Le but serait dès qu’un contrat passe en « archivé », celui-ci apparaisse dans un onglet « contrat archivé » et plus dans la liste des contrats. (ci dessous au niveau de l’état).

![image](https://user-images.githubusercontent.com/36480918/47647659-edae1480-db77-11e8-8258-42e2cf482bba.png)
@badreloifi @MamboJoel
