### ISSUE TITLE
FACTURATION LLD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#13]
[42304_11991_2018_3 (1).pdf](https://github.com/Lenormant/location/files/1774660/42304_11991_2018_3.1.pdf)
![image](https://user-images.githubusercontent.com/36480918/36894913-50a7cb0e-1e0d-11e8-8636-c6d6fec69934.png)

Bonjour,
En PJ la facture 20055313 LBD. Vous pourrez constater que le montant total ne correspond pas à la somme de tous les loyers.
Merci de modifier celle-ci afin que je puisse la générer à nouveau.

**Comment by HANNIERMC** [comment]
Bonjour pourriez vous voir ce problème aujourd’hui. Nous ne pouvons envoyer la facture au client. merci d'avance.
@jlenormant @meillere

**Comment by meillere** [comment]
Bonjour,
Je n'ai pas la même facture.
j'ai imprimé à partir de là
![image](https://user-images.githubusercontent.com/22621226/37022942-595a073c-211c-11e8-9a7b-8efd1782324e.png)
et j'ai
![image](https://user-images.githubusercontent.com/22621226/37022974-71401f1c-211c-11e8-8287-6ba15dba7296.png)
Il serait intéressant de voir tous le process qui à permis d'avoir cette facture vraisemblablement une modification de la facture générée et une impression avant enregistrement des modifications et recalcul du pied de facture.

**Comment by HANNIERMC** [comment]
Bonjour,
J’ai la même facture effectivement. En gros, je devrais avoir en total : 4189,20 € HT
J’ai du faire une modification car certains contrats n’avaient pas été prolongés en mars. J’ai du annuler la facture générée et prolonger les contrats afin qu’ils s’ajoutent à la facture. Mais du coup, comment rattraper le tir ?Le bon montant total devrait être 4189,20 € HT et la facture sort à 4191,12 € HT
Merci de votre aide,
@meillere @jlenormant

**Comment by HANNIERMC** [comment]
bonjour nous lançons les prélèvments ce jour, merci de supprimer la facture 20055144 et de modifier la facture 20055313 en enlevant le montant de 4191,12 € HT qui est erroné et mettre 4189,20 € HT.
@meillere 
@jlenormant

**Comment by HANNIERMC** [comment]
on peut clore cette issue, l'assistante fait un avoir en interne pour la facture de trop. Il y a juste une cession qui n’a pas été réindexée, et qui sera modifiée le mois prochain.
Merci
