### ISSUE TITLE
LISTE DES CONTRATS LCD CHEZ UN CLIENT

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#15]
![image](https://user-images.githubusercontent.com/36480918/36973028-a60ce096-2071-11e8-89a9-b81bdc1c8476.png)

bonjour Serait il possible d'avoir tous les contrats LCD d'un même client avec le montant du contrat sous format EXCEL (ONGLET CLIENTS-LISTE DES CONTRATS CLIENTS)

**Comment by HANNIERMC** [comment]
Bonjour pourriez vous me tenir informée de l'état d'avancement des différentes demandes.
merci d'avance
@jlenormant @meillere

**Comment by meillere** [comment]
J'ai rectifié

**Comment by HANNIERMC** [comment]
Pour les contrats en cours ou terminés il me faudrait le montant facturé et non le montant du devis.


![image](https://user-images.githubusercontent.com/36480918/38558760-690fb21e-3cd1-11e8-95b3-4d473da75b37.png)

**Comment by HANNIERMC** [comment]
parfait merci. je cloture
