### ISSUE TITLE
ANNULATION FACTURE LLD PAR ERREUR

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#19]
Marie-Claire, j’ai annulé la facture d’avril pour le contrat ci-dessous par erreur merci de demander qu’il me la remette dans mes facture à éditer d’avril.

 
![image](https://user-images.githubusercontent.com/36480918/38306878-367419c6-3812-11e8-91d7-e554b08bdc63.png)

**Comment by HANNIERMC** [comment]
Marie-Claire, j’ai annulé la facture d’avril pour le contrat ci-dessous par erreur merci de demander qu’il me la remette dans mes facture à éditer d’avril.


![image](https://user-images.githubusercontent.com/36480918/38306912-54979e8c-3812-11e8-8b1c-164f692095fd.png)
@jlenormant @meillere

**Comment by meillere** [comment]
Bonjour Marie Claire,

c'est fait




2018-04-04 13:13 GMT+01:00 HANNIERMC <notifications@github.com>:
