### ISSUE TITLE
PROBLEME FACTURATION LLD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#24]
Marie Claire,

Pourrais tu faire suivre l’email à Waybis, pour qu’il regarde s’il n’y a pas un problème.
J’ai du retourner sur la facture 90057285 pour ajouter le numéro de commande client et ce jour, nous nous sommes rendu compte qu’une facture a été générée en double pour cette même cession soit la facture 90057677.
[SUEZ RV OSIS FM.pdf](https://github.com/Lenormant/location/files/2027247/SUEZ.RV.OSIS.FM.pdf)

@jlenormant @meillere

**Comment by badreloifi** [comment]
Bonjour @HANNIERMC,

Ce problème est-il toujours d'actualité ?
Je pense que la facture a dû être dupliqué c'est pour cela qu'elle a été générée en double.

**Comment by HANNIERMC** [comment]
Les personnes susceptibles de répondre sont en congés. je vois d'ici à 15 jours. on peut mettre en santd by les problèmes LLD pendant cette période. Nous sommes disponibles pour les problèmes LCD
@badreloifi

**Comment by badreloifi** [comment]
D'accord pas de soucis !

@HANNIERMC
