### ISSUE TITLE
URGENT PROBLEME COMPTABLE FACTURATION

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#26]
[Probleme facturation remise en route.pdf](https://github.com/Lenormant/location/files/2067254/Probleme.facturation.remise.en.route.pdf)

Bonjour veuillez trouver PJ + mail problème facturation LLD

Bonjour, j’ai 7 factures qui se sont arrêtés au 31/05/2018 que j’ai repoussé à la date de fin de contrat au 31/12/2018 vendredi dernier. Mais ce matin elles n’apparaissent pas dans mes factures à éditer. Merci de faire le nécessaire dès que possible.

**Comment by HANNIERMC** [comment]
@MamboJoel @Paulhac @jlenormant @meillere

**Comment by meillere** [comment]
Pour une raison que j'ignore la tache programmée sur le serveur NTLM01 a cessé de s’exécuter le 31/5 probablement a cause de modification des droits.
Je l'ai relancée manuellement pour créer les factures, mais il faut regarder le problème de lancement de la tache parametrée.
![image](https://user-images.githubusercontent.com/22621226/40907494-f492393a-67db-11e8-9599-a5b1bc66bed2.png)

**Comment by meillere** [comment]
![image](https://user-images.githubusercontent.com/22621226/40907552-215dd2da-67dc-11e8-8fc2-ec999059572f.png)

**Comment by meillere** [comment]
![image](https://user-images.githubusercontent.com/22621226/40907590-3f5a6e6a-67dc-11e8-9cec-8ed4212e7264.png)
