### ISSUE TITLE
URGENT BUG FACTURES LCD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#27]
bonjour toutes les factures de location courte durée du mois de mai sont sorties à la date d'aujourd'hui. merci de nous les ressorti à la date du 31 mai
@MamboJoel @Paulhac @jlenormant @meillere

**Comment by HANNIERMC** [comment]
bonjour
les factures et avoir LCD sont sorties à la date du 06 juin alors qu'elles ont été saisies au 31 mai.
Dans crédel ces factures sont comptabilisées au 6 juin au lieu du 31 mai. merci de rectifier pour qu'elles passent bien en mai et que cela ne se reproduise pas le mois prochain
69010135
69010133
69010134
69010132
69010136
69010134


29010129
29010137
29010130
@MamboJoel @Paulhac @jlenormant @meillere

**Comment by MamboJoel** [comment]
Bonjour,

Nous maintenons le site internet, mais nous n'avons pas accès à Credel. Il faut changer ces dates dans ce logiciel. Pouvez-vous voir avec Hamid Lebied ?

**Comment by HANNIERMC** [comment]
ok et de votre côté merci de voir pour les prochains mois
@MamboJoel
