### ISSUE TITLE
DEMANDE MODIFICATION CONTRAT LLD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#28]
[Probleme besoin chgt cpte.pdf](https://github.com/Lenormant/location/files/2068622/Probleme.besoin.chgt.cpte.pdf)
@MamboJoel @Paulhac @jlenormant @meillere

**Comment by HANNIERMC** [comment]
Bonjour Paulhac pourriez vous finaliser ce jour, nous devons clôturer les factures ce soir.
Merci
@Paulhac @jlenormant @meillere

**Comment by Paulhac** [comment]
C'est fait
