### ISSUE TITLE
En l'absence d'un bon de reprise : bloquer le véhicule.

### ISSUE THREAD

**Issue by MamboJoel** [Lenormant/location#3]
# Scénario 

1. Un véhicule est prêté jusqu'à un jour J.
1. Au jour J, aucun bon de reprise n'est enregistré (le client l'a gardé ou l'on n'a pas entré de bon de reprise dans l'application).
1. Dès lors le véhicule reste disponible dans l'application.
1. Et il se trouve sujet à d'autres locations.

# Solution

Alerter l'utilisateur qui au point 4. voudrait à nouveau louer le véhicule.

@HANNIERMC pouvez-vous confirmez ce scénario et cette solution souhaitée ?

**Comment by HANNIERMC** [comment]
Nicolas je vous confirme ce scénario. Il y en a un deuxième : le véhicule est "reservé" du 01/09/2018 au 30/09/2018 (réservé veut dire que nous avons la commande et qu'il va vraiment être loué). Là aussi nous ne devons être alertés qu'il y a une réservation en cours afin de ne pas démarrer une location du 01/03/2018 jusqu'au 30/11/2018.

**Comment by MamboJoel** [comment]
J'en ai discuté avec Jacques et cette demande pose problème.

Si l'on vous alerte alors que vous vous apprêtez à créer une location pour un véhicule auquel il manque un bon reprise : nous vous alertons systématiquement. 

Pour régler ces cas l'application propose les états de relances et de retard. Ils ne vous conviennent pas ?

**Comment by HANNIERMC** [comment]
pourriez vous annuler au plus vite. Merci
@jlenormant @meillere
