### ISSUE TITLE
FACTURATION LCD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#30]
bonjour
dans le programme LCD Facturation la colonne "DUPPLIQUER"  à côté de la colonne "Faire AVOIR" a disparu. Pourriez vous la réactiver.
merci

![image](https://user-images.githubusercontent.com/36480918/41026820-cbac63e2-6975-11e8-8da7-87348967582b.png)
@MamboJoel @Paulhac @jlenormant @meillere

**Comment by HANNIERMC** [comment]
encore disparu ce jour
@badreloifi

**Comment by badreloifi** [comment]
c'est fait pouvez-vois vérifier s'il vous plaît ?
@HANNIERMC

**Comment by HANNIERMC** [comment]
c'est Ok
@badreloifi

**Comment by badreloifi** [comment]
@HANNIERMC, Parfait pouvez-vous clôturer l'issue s'il vous plaît.

**Comment by HANNIERMC** [comment]
bonjour le problème est revenu ce jour.
@badreloifi @jlenormant

**Comment by HANNIERMC** [comment]
bonjour pourriez vous régler ce problème. merci
@badreloifi @jlenormant

**Comment by jlenormant** [comment]
Bonjour, je pense avoir trouvé le problème, en revanche le lien avait été explicitement désactivé. Y a-t-il une raison à votre avis ?

**Comment by HANNIERMC** [comment]
absolument aucune raison que cela ait été désactivé
@jlenormant

**Comment by HANNIERMC** [comment]
bonjour Jean est-ce débloqué ?
@jlenormant

**Comment by jlenormant** [comment]
J'ai rétabli le lien

**Comment by HANNIERMC** [comment]
ok ça fonctionne
@jlenormant
