### ISSUE TITLE
CONNEXION LOGICIEL LOCATION INTROUVABLE

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#34]
Bonjour Plus de connexion au site depuis hier. "ce site est inaccessible" ou "ce site est introuvable"
@MamboJoel @Paulhac @jlenormant @meillere

**Comment by MamboJoel** [comment]
@HANNIERMC avec quelle URL (adresse dans votre navigateur) accédez vous au site ?

**Comment by meillere** [comment]
Bonjour,
le site fonctionne.
j'accède par lcd.waybis.com.
Autant que je me souvienne le site n'est accessible que de certaines adresses IP
( adresses interne du groupe Lenormant )
on avait mis en place une sécurité IPSec

![image](https://user-images.githubusercontent.com/22621226/42282703-a8f207a6-7fa7-11e8-9816-46976ee2a454.png)

**Comment by HANNIERMC** [comment]
Marie-Claire HANNIER
mchannier@lenormant.fr
06.14.90.93.88

Le 4 juil. 2018 à 16:32, meillere <notifications@github.com> a écrit :

Bonjour,
le site fonctionne.
j'accède par lcd.waybis.com.
Autant que je me souvienne le site n'est accessible que de certaines adresses IP
( adresses interne du groupe Lenormant )
on avait mis en place une sécurité IPSec

**Comment by HANNIERMC** [comment]
celà re fonctionne mais je n'ai plus eu accès pendant 24h
et je me connecte habituellement sur http://loclm.lenormant.fr/
