### ISSUE TITLE
DEMANDE DE MOFICATION COMPTABLE POUR LLD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#35]
Bonjour Marie-Claire,

Merci de transférer ma demande ci-dessous à Waybis.

Merci

Nous avons le client VETROTECH sous St Quentin qui a 13 contrats de location longue durée qui sont prélevés.
Aujourd’hui ce client change de RIB.
Etant donné que les 13 contrats de ce client porte le même n° de regroupement, soit le 11838.
Je souhaitais savoir comment faire pour modifier le RIB une seule fois, dans ce regroupement.
Ce qui évite de modifier 13 fois le RIB pour les 13 contrats différents.

Pourriez-vous m’indiquer la marche à suivre pour modifier un regroupement.

@Portekoi @MamboJoel @Paulhac @jlenormant @meillere

**Comment by MamboJoel** [comment]
NB  vu notre charge actuelle les congés en cours et surtout que cette issue est classée parmi les plus urgentes : est-il possible que vous effectuiez ces 13 changement à la main, via l'application ?
Sachez que pour que @Portekoi ou moi le fassions par programmation il va nous falloir nous plonger dans le code, dans la base de données et cela risque de prendre beaucoup plus de temps.
