### ISSUE TITLE
BUG COMPTE CLIENT ENTRE WAYBIS ET CREDEL

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#36]
![image](https://user-images.githubusercontent.com/36480918/43070562-6e306432-8e70-11e8-8a70-0323caa6fffa.png)

Incompatibilité entre Waybis et Credel qui refuse mon compte client 33139 CH St quentin
@Portekoi @MamboJoel @Paulhac @jlenormant @meillere

**Comment by HANNIERMC** [comment]
URGENT MERCI
même problème
![image](https://user-images.githubusercontent.com/36480918/43085164-83e41ed4-8e9a-11e8-9908-ef7fc1513bae.png)


@Portekoi @MamboJoel @Paulhac @jlenormant @meillere

**Comment by MamboJoel** [comment]
Merci de nous communiquer le lien (l'url, ce qu'il y a dans la barre d'adresse) à chaque fois que vous nous envoyez une copie d'écran. Ca nous est indispensable pour reproduire l'anomalie.

Quelle est donc le lien de cette anomalie ?

**Comment by HANNIERMC** [comment]
http://lcd.waybis.com/lcd/PlanningLCD.aspx?Action=FaireLCD


mchannier@lenormant.fr
mot de passe : hannier

**Comment by HANNIERMC** [comment]
pour le1er cas nous avons essayé en vain. Pour le second cas ça fonctionne
http://lcd.waybis.com/lcd/infosclient.aspx?Client ID=13381
@MamboJoel

**Comment by badreloifi** [comment]
Bonjour @HANNIERMC, 
Pouvez-vous m'indiquez la marche à suivre pour reproduire l'erreur du premier cas s'il vous plait ?

**Comment by HANNIERMC** [comment]
-Waybis ne reconnait pas le compte du client qui existe dans Credel : 33139 

![image](https://user-images.githubusercontent.com/36480918/43326754-e7cddc10-91b9-11e8-8b9c-6c0bfd268e69.png)

![image](https://user-images.githubusercontent.com/36480918/43326810-09421d5c-91ba-11e8-86e2-055f0555d326.png)

-De ce fait, je veux créer un nouveaux client, et message d'erreur :
![image](https://user-images.githubusercontent.com/36480918/43326850-1f3ec2f4-91ba-11e8-9245-32525cb2f576.png)
@badreloifi

**Comment by Portekoi** [comment]
Afin de vous aider au mieux, il faudrait détailler les étapes pour arriver à l'écran d'erreur. 

Par exemple,  j'ai recherché parmi les clients "Centre" ce qui me donne cette liste : 

![image](https://user-images.githubusercontent.com/1560754/43357550-c5cef64c-9283-11e8-984d-e58b103c7358.png)

J'ai bien le client `Centre Hospital de Saint Quentin` 

Je cliquer sur le bouton à gauche et je vois cet écran : 

![image](https://user-images.githubusercontent.com/1560754/43357561-edec0caa-9283-11e8-800d-a3cdc95a31a2.png)

Mais ensuite, que faire pour reproduire l'écran? Quels champs avez vous saisis par exemple?

Merci

**Comment by HANNIERMC** [comment]
Chemin à suivre :
-Planning
-Faire résa LCD
dans la case client taper le numéro 33139 puis recherche Crédel. Et à ce stade rien ne se passe alors que le compte existe bien dans Crédel.

-reprendre Issue de vendredi
@badreloifi

**Comment by Portekoi** [comment]
Je viens de taper `33139` mais je n'arrive pas jusqu'à l'erreur mentionnée ci-dessus. 

![image](https://user-images.githubusercontent.com/1560754/43385207-67e08bc8-93e0-11e8-81f6-98a3c202b428.png)

Ensuite? Que faites-vous? Nouveau client? Quelles données insérez vous? 

Désolé pour les questions mais je dois reproduire l'anomalie afin de la corriger.

**Comment by HANNIERMC** [comment]
pourriez vous m'appeler sur mon portable au 06 14 90 93 88 je vous passerai l'assisante qui a un autre cas ce jour.
merci
@badreloifi

**Comment by Portekoi** [comment]
@badreloifi Si tu as fermé, détail la solution s'il te plait que l'on est un historique.

**Comment by badreloifi** [comment]
@Portekoi Oui désolé,

enfaîte dans le pool d’application les applications 32 bits n'était pas activé, je l'ai donc activé en allant sur le pool lenormant.loclm2, dans paramètre avancées j'ai mis en True le paramètre "activer les applications 32 bits

**Comment by Portekoi** [comment]
Flûte je pensais l'avoir activé. Bien joué et merci !
