### ISSUE TITLE
FACTURATION LLD AU 20 JUILLET

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#37]
![image](https://user-images.githubusercontent.com/36480918/43125130-6d5250de-8f29-11e8-9604-aca3b82e8f53.png)

bonjour la liste des factures à éditer au 20 juillet n'apparait pas. Voir chemin sur PJ
@MamboJoel

**Comment by HANNIERMC** [comment]
Lien : http://lcd.waybis.com/default.aspx

avez vous besoin de mes mots de passe
@MamboJoel

**Comment by MamboJoel** [comment]
Oui il me faut tout. login mot de passe.

**Comment by HANNIERMC** [comment]
http://loclm.lenormant.fr/LLD/LLDInvoicing.aspx?Type=ToPrint

identifiant : mchannier@lenormant.fr
mot de passe : hannier
vous pouvez les utiliser pour toutes les issues
