### ISSUE TITLE
ACCES LCD PLAN JOUR IMPOSSIBLE

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#38]
la page d'accès reste muette

http://lcd.waybis.com/reporting/Planjour.aspx

![image](https://user-images.githubusercontent.com/36480918/43273583-19969c36-90fd-11e8-8250-deb014ef0ab1.png)
@MamboJoel

**Comment by badreloifi** [comment]
Bonjour @HANNIERMC,
Pouvez-vous vérifier si le problème a été réglé s'il vous plait ?

**Comment by HANNIERMC** [comment]
c'est OK ça fonctionne. Je clôture l'Issue. Merci

**Comment by HANNIERMC** [comment]
@badreloifi 
j'avais oublié l'indiquer votre adresse
