### ISSUE TITLE
Exonération de TVA

### ISSUE THREAD

**Issue by MamboJoel** [Lenormant/location#4]
# Problématique

Les factures éditées le sont toujours avec TVA. 
Or l'application travaille également en exonération.

# Piste

`LCD/infosclient.aspx`

Cette page présentant la configuration du client et de ses contrat montre une coche "exonération". Elle ne semble pas câblée.

**Comment by HANNIERMC** [comment]
bonjour ça ne fonctionne toujours pas
@jlenormant @meillere

**Comment by HANNIERMC** [comment]
problème résolu
@badreloifi
