### ISSUE TITLE
IMPOSSIBLE DE CREER CONTRAT LCD (clémence)

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#40]
impossible de créer un contrat LCD dans divers L6999 ID N°21031

![image](https://user-images.githubusercontent.com/36480918/44325926-6f881000-a45a-11e8-8605-a0092914a8e1.png)
@Portekoi @Paulhac @badreloifi

**Comment by Portekoi** [comment]
@badreloifi Des nouvelles?

**Comment by HANNIERMC** [comment]
ça  fonctionne. Je vous laisse clôturer l'issue
@Portekoi @badreloifi
