### ISSUE TITLE
ERREUR CREATION COMPTE CONTRAT LLD FLORENCE

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#42]
Bonjour avez vous la possibilité de corriger erreur de création compte 

client 49533 SAS SPONTEX au lieu de 49599 SPONTEX SAS.
Cession U1001 à U1009. Est-il possible de basculer les cessions sur le compte 49599.

Autre chose, serait-il possible de créer en LLD un onglet « contrat archivé ». Le but serait : dès qu’un contrat est terminé donc archivé qu’il n’apparaisse plus dans les contrats en cours pour plus de lisibilité.

![image](https://user-images.githubusercontent.com/36480918/46007278-f2376700-c0b9-11e8-9137-92d639f00f63.png)
![image](https://user-images.githubusercontent.com/36480918/46007314-0bd8ae80-c0ba-11e8-9bbe-1b0ad88b9eb8.png)
@Portekoi @Paulhac @badreloifi

**Comment by Paulhac** [comment]
C'est fait. merci de clôturer l'issue
