### ISSUE TITLE
Facturation groupée

### ISSUE THREAD

**Issue by MamboJoel** [Lenormant/location#5]
La longue durée permet les facturation groupées. Elle est souhaitée également par les clients en courte durée.

**Comment by HANNIERMC** [comment]
Bonjour pourriez vous traiter ce sujet
merci
@Portekoi @Paulhac @badreloifi

**Comment by HANNIERMC** [comment]
bonjour relance de ce dossier. Merci
@jlenormant @Portekoi @Paulhac @badreloifi

**Comment by MamboJoel** [comment]
@meillere tu peux nous donner une indication sur la faisabilité de cette demande ?

**Comment by HANNIERMC** [comment]
pour info ce programme existe déjà sur la partie LLD
@MamboJoel @meillere
