### ISSUE TITLE
URGENT CHARIOT + CONTRAT LCD DISPARU

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#51]
bonjour Jean 
le chariot L6016 a disparu du planning et donc le contrat qui est dessus en cours de location également. 
la dernière facture est sortie vendredi matin et ce matin il n'y avait plus rien.
Paulhac n'a pas trouvé
@jlenormant

**Comment by jlenormant** [comment]
ce chariot est indiqué comme en fin de gestion au 31/1/2017, je ne sais pas pourquoi. Avez-vous un accès pour réactiver les chariots archivés ?

**Comment by jlenormant** [comment]
On le retrouve dans "materiel"->"export xls" et il est indiqué qu'il est supprimé, en revanche je ne sais pas comment consulter sa fiche

**Comment by HANNIERMC** [comment]
on ne peut plus consulter la fiche chariots si celle si est supprimée mais elle ne l'est pas totalement puisque elle est encore dans "materiel"->"export xls
effectivement il existe un accès que Jacques Meillère connait pour réactiver les chariots archivés. Moi pas et je ne comprends pas comment il a pu être supprimé. je suis la seule à avoir accès au création et suppression de chariots
@jlenormant

**Comment by jlenormant** [comment]
Je peux le réactiver directement dans la base de données pour l'instant.
Je conserve la date d'entrée en parc au 26/10/2015 et je supprime la date de sortie de parc

**Comment by HANNIERMC** [comment]
c'est parfait. Merci Jean. Par ailleurs, ce même contrat avait déjà disparu en avril 2018.

Pour archiver les chariots j'utilise "matériel, liste LCD
http://lcd.waybis.com/Gestion/Vehicles.aspx
@jlenormant

**Comment by HANNIERMC** [comment]
puis je précise une date de sortie, je sauvegarde et ensuite je clique sur la croix rouge pour supprimer. Ces sorties sont ensuite archivées dans un fichier dont je n'ai pas accès
@jlenormant

**Comment by HANNIERMC** [comment]
pour cette utilisation c'est bien cela, ce qui permet de créer, supprimer ou modifier la configuration.Il n'y a rien d'autre
@jlenormant
