### ISSUE TITLE
URGENT LCD L'OPERATION DUPLIQUER UN CONTRAT  EST IMPOSSIBLE

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#52]
Ce matin en ouvrant Waybis,  la configuration a été modifié ( les onglets différents)
Et en voulant dupliquer un contrat du L3406 vers L3408, j’ai eu ce msg d’erreur …
Merci de transmettre stp.

![image](https://user-images.githubusercontent.com/36480918/52341307-81fb0380-2a12-11e9-9e39-8c9a1ebe8e19.png)
@jlenormant

**Comment by HANNIERMC** [comment]
Bonjour pourriez vous nous régler ce problème. Merci
@jlenormant

**Comment by jlenormant** [comment]
J'ai du mal à reproduire le problème.

Il s'agit bien de faire un clic-droit sur un contrat et choisir "dupliquer" ? Le message d'erreur s'affiche immédiatement après le clic sur "dupliquer" ?

**Comment by HANNIERMC** [comment]
Au niveau du clic droit pour dupliquer on ajoute une cession et après validation nous avons le message d’erreur 
@jlenormant

**Comment by HANNIERMC** [comment]
bonjour Jean avez vous trouvé
@jlenormant

**Comment by jlenormant** [comment]
Je n'ai pas réussi à reproduire le problème de mon côté.

En revanche j'ai fait une ou deux modifications qui ont peut-être résolu le problème avant. Pouvez-vous réessayer ?

Si ça ne marche pas est-ce que je peux faire des tests en ligne ? sur quels contrats ? y a-t-il un moyen de les supprimer ensuite ?

**Comment by HANNIERMC** [comment]
vous pouvez dupliquer le L3349 sur le contrat D6000
@jlenormant

**Comment by jlenormant** [comment]
C'est rétabli !

**Comment by HANNIERMC** [comment]
youpi en plus ça fonctionne
@jlenormant
