### ISSUE TITLE
URGENT FACTURATION LCD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#53]
![image](https://user-images.githubusercontent.com/36480918/52350014-f68c6d00-2a27-11e9-88a1-49c6ee22c46d.png)

Les 3 factures ci-jointes ont été établies hier mais ne sont pas passées cette nuit dans la routine Crédel
@jlenormant

**Comment by jlenormant** [comment]
Vu aujourd'hui. Pouvez-vous confirmer que c'est rétabli ?

**Comment by HANNIERMC** [comment]
c'est rétabli
@jlenormant
