### ISSUE TITLE
URGENT PLUS D'ACCES AU PLANNING LCD

### ISSUE THREAD

**Issue by HANNIERMC** [Lenormant/location#56]
![image](https://user-images.githubusercontent.com/36480918/53029792-e33ac200-3469-11e9-87b9-57f04e25d9a5.png)
@jlenormant @Portekoi @Paulhac @badreloifi

**Comment by jlenormant** [comment]
Il y a eu une opération de maintenance, çça doit être rétabli

**Comment by HANNIERMC** [comment]
ok
@jlenormant
