### ISSUE TITLE
Listing des factures

### ISSUE THREAD

**Issue by MamboJoel** [Lenormant/location#6]
On souhaite qu'il soit trié par ordre alphabétique des clients.
@HANNIERMC pouvez-vous préciser le "chemin" de ce listing de factures ?

**Comment by HANNIERMC** [comment]
ONGLET FACTURATION-PROCHAINE FACTURATION MENSUELLE
-on sélectionne  une agence
à ce premier  état du processus facturation une première liste de clients dans le désordre apparait à l'écran dans le désordre mais on peut agir en cliquant sur société pour faire apparaitre par ordre alphabétique
-on enregistre
-ensuite on passe à l'ONGLET : LCD FACTURES A EDITER
à cet état la liste des factures à éditer apparait dans le désordre et on ne peut agir. C'est pour ces 2 applications que nous souhaiterions un ordre alphabétique d'office.

aujourd'hui nous ne sommes pas à la date du 20 pour lancer les factures et ne je ne peux vous envoyer de copie d'écran

**Comment by MamboJoel** [comment]
LCD/ProchaineMens.aspx quand on clique sur "SOCIETE" les première lignes s'ordonne, pas les suivantes.

**Comment by HANNIERMC** [comment]
ci joint extrait
![listing factures](https://user-images.githubusercontent.com/36480918/36849588-b7859c2e-1d64-11e8-9c0d-2419962c26e8.jpg)

**Comment by MamboJoel** [comment]
C'est à cause des espaces. Ils viennent certainement de Credel :

![image](https://user-images.githubusercontent.com/3832009/36849917-95219cb8-1d65-11e8-9569-f051958c8026.png)

**Comment by HANNIERMC** [comment]
Bonjour pour info cette liste sortait bien par ordre alphabétique il y a quelques mois.
@jlenormant @meillere

**Comment by badreloifi** [comment]
Bonjour @HANNIERMC , 
Pouvez-vous vérifier si cela fonctionne bien s'il vous plait ?

**Comment by HANNIERMC** [comment]
![image](https://user-images.githubusercontent.com/36480918/43717497-0fe06a12-9988-11e8-8ce9-cdc245ae7eef.png)


toujours pas

**Comment by badreloifi** [comment]
@HANNIERMC,
Ah, je pensais que cela devait être fait pour les prochaines facturations mensuelles et les factures à éditer, mais le lien de votre capture d'écran affiche autre chose.

**Comment by HANNIERMC** [comment]
le problème est le même pour le listing des factures mensuelles que nous ne pouvons sortir qu'à partir du 20 de chaque mois, et pour le listing des factures de location de moins de 1 mois
@badreloifi

**Comment by badreloifi** [comment]
@HANNIERMC , 
pouvez-vous vérifier que cela fonctionne s'il vous plaît ? et ensuite clore l'issue si résolu.

**Comment by HANNIERMC** [comment]
bonjour le problème est de nouveau réapparu. Pourriez vous intervenir. Merci
@badreloifi @Portekoi @Paulhac

**Comment by badreloifi** [comment]
Bonjour @HANNIERMC ,
pouvez-vous vérifiez que cela fonctionne s'il vous plaît ? et ensuite clore l'issue si résolu.

**Comment by HANNIERMC** [comment]
ça fonctionne pour les locations de moins de 1 mois mais pas pour les locations mensuelles
@badreloifi

**Comment by badreloifi** [comment]
pouvez-vous vérifiez si cela fonctionne pour les locations mensuelles s'il vous plaît ?

**Comment by HANNIERMC** [comment]
non toujours pas
@badreloifi

**Comment by badreloifi** [comment]
pourriez-vous me donner les étapes pour vérifier cela s'il vous plaît ?

**Comment by HANNIERMC** [comment]
![image](https://user-images.githubusercontent.com/36480918/47160908-369cd800-d2f1-11e8-85f4-f61451d6af90.png)
@badreloifi

**Comment by badreloifi** [comment]
Cela devrait être bon pouvez vous vérifiez et clore l'issue si résolu s"il vous plaît ?

**Comment by HANNIERMC** [comment]
c'est OK
@badreloifi
