### ISSUE TITLE
Planning à J plutôt que J-1

### ISSUE THREAD

**Issue by MamboJoel** [Lenormant/location#7]
`Reporting/PlanningJour.aspx`

Cette page affiche un planning au jour J-1. Or il est déjà obsolète. On souhaite ce même planning mais au jour J.

**Comment by jlenormant** [comment]
Je viens de mettre en ligne une modification qui a 'air de fonctionner
il n'y a plus que 2 statuts : "libre" et "indisponible"
j'ai aussi ajouté aux chariots libres les dates de prochaine location s'il y a une location confirmée dans le futur

**Comment by HANNIERMC** [comment]
effectivement il n'y a plus que 2 statuts qui ne permettent pas de savoir si le matériel est en location chez un client ou rééllement en location, formation ....
il est toujours à J-1
@jlenormant

**Comment by jlenormant** [comment]
- Pouvez-vous me donner la liste des statuts que vous souhaitez voir ?
- Pouvez-vous me donner un exemple pour le "J-1" ? Ce sont les données de location en temps réel, donc il ne doit pas y avoir de décalage.

**Comment by HANNIERMC** [comment]
Liste des statuts :libre, contrats en cours, loué, indisponible, pret, demo, formation

![image](https://user-images.githubusercontent.com/36480918/52059549-68694000-256a-11e9-8dab-d1ab101c969b.png)
@jlenormant

**Comment by jlenormant** [comment]
Ah effectivmeent, j'ai oublié de modifier la date.

En revanche je ne vois pas de différence entre "contrat en cours" et "loué", est-ce la même chose ?

**Comment by HANNIERMC** [comment]
loué = commande passée mais pas livré
en cours = location en cours
après discussion avec les assistantes il faut laisser les 2 statuts car le statu loué permet de supprimer le contrat en cas d'annulation de la part du client avant la livraison. 
@jlenormant

**Comment by jlenormant** [comment]
est-ce qu'il y a une action qui marque le chariot comme livré (et donc passe le statut de "loué" à "en cours") ? ou est-ce que cela dépend uniquement des dates de début et fin de contrat ?

**Comment by HANNIERMC** [comment]
pourriez vous restaurer les statuts : contrats en cours, loué,  pret, demo, formation et modifier la date pour voir apparaitre la date du jour
@jlenormant

**Comment by jlenormant** [comment]
Je viens de mettre en ligne une modification

**Comment by jlenormant** [comment]
Apparemment "contrat en cours" est vide parce que la sortie du chariot n'a pas été entrée, donc les contrats restent au statut "loué"
